### ISSUE TITLE
How do you send parameters in command line?

### ISSUE THREAD

**Issue by stevevance** [openaddresses/pyesridump#15]
````
esri2geojson -p "outFields=PIN14" http://gis2.cookcountyil.gov/arcgis/rest/services/cookVwrDynmcCondo/MapServer/44 condos_pins.geojson
````

returns:
````
Traceback (most recent call last):
  File "/usr/local/bin/esri2geojson", line 9, in <module>
    load_entry_point('esridump==1.1.1', 'console_scripts', 'esri2geojson')()
  File "/Library/Python/2.7/site-packages/esridump/cli.py", line 63, in main
    params = _collect_params(args.params)
  File "/Library/Python/2.7/site-packages/esridump/cli.py", line 22, in _collect_params
    params.update(dict(urllib.parse.parse_qsl(string)))
AttributeError: 'module' object has no attribute 'parse'
````

**Comment by iandees** [comment]
If you `pip install -U esridump==1.2.0` you should be able to do this:

```
esri2geojson -f PIN14 --no-geometry http://gis2.cookcountyil.gov/arcgis/rest/services/cookVwrDynmcCondo/MapServer/44 condos_pins.geojson
```

This'll give you a GeoJSON file with no geometry and just the PIN14 field.

**Comment by iandees** [comment]
I"m going to close this because:

- Sending parameters was broken (due to a Python imports error) and fixed by #17
- Specifying the list of fields you want (which is what I see you actually wanted in your example) was added in #18

**Comment by stevevance** [comment]
It worked for me, thanks.

**Comment by stevevance** [comment]
I had to reference this issue today, 7 years later and I'm still using this tool to ingest ArcGIS-hosted datasets.
